### ISSUE TITLE
Error trying to run 'npm run dev'

### ISSUE THREAD

**Issue by ilbelon** [grimimirg/dungeoncave#1]
While try 'npm run dev' i got:
 Cannot find module '...\build\webpack.dev.conf.js'

**Comment by ilbelon** [comment]
Ok the file is there but i got this error runninf 'npm run dev':

 94% asset optimization

 ERROR  Failed to compile with 1 errors                                                                         12:35:30

 error  in ./src/mixins/storeUtility.js

Syntax Error: Unexpected token (5:4)

  3 | export default {
  4 |   computed: {
> 5 |     ...mapGetters({getLabels: 'getLabels'}),
    |     ^

**Comment by grimimirg** [comment]
Problem is about the three dots before `mapGetters`. Which IDE are you running? Are you using ECMA6 compiler?

**Comment by ilbelon** [comment]
windows powershell xD

**Comment by grimimirg** [comment]
Try to create a `.babelrc` on you project's root within it

`{
  "presets": [
    "stage-2"
  ],
  "plugins": [
    "transform-vue-jsx",
    "transform-runtime"
  ]
}
`

it should allow `npm run dev` to understand that code.
